#!/bin/bash

run_npm() {
  if type_exists 'npm'; then
    e_header "Installing Node.js packages..."

    # List of npm packages
    local packages="bower grunt-cli gulp karma"

    # Install packages globally and quietly
    npm install $packages --global --quiet

    [[ $? ]] && e_success "Done"
  else
    e_error "Error: npm not found."
    printf "Aborting...\n"
    exit
  fi
}